### ISSUE TITLE
Intégration Naviclim - TAKAO M3

### ISSUE THREAD

**Issue by alicesalse-bmg** [gduteil/cozytouch#1]
Bonjour @gduteil ,

Merci pour ce début d'intégration. J'ai pu m'en servir pour connecter mon pack naviclim avec mes clims réversibles Takao M3.

J'ai chargé toutes les entités inconnues et voici les déductions que j'ai pu faire :

![cozytouch_ha](https://github.com/gduteil/cozytouch/assets/147829707/d04db7e2-9f31-4ded-95dc-71abe44d6f13)
![cozytouch_ha2](https://github.com/gduteil/cozytouch/assets/147829707/8f1fa093-cb00-4589-8307-4ce0be2069c8)

J'ai pas encore eu le temps de regarder trop en détail votre code mais si je peux je pousserai mes contributions.

En effet, je voudrais arriver à gérer aussi : cool / dry / fan / auto en plus de heat.

Bonne soirée.

**Comment by gduteil** [comment]
Bonsoir et merci pour le retour.

Pour résumer :
- 100505 : Mode Powerful -> contrôle (0 ou 1)
- 100506 : Detection présence -> état (0 ou 1)
- 100507 : Mode eco -> contrôle (0 ou 1)
- 100801 : FAN speed -> contrôle (1 à 4 + 5 pour auto)
- 100802 : Quiet mode -> contrôle (0 ou 1)
- 100804 : Position volets -> contrôle (1 à 4)
- 166 : Mode basic/prog -> contrôle (411 ou 25)

100800 et 100803 me paraissent étranges, ils évoluent en fonction du mode mais sont identiques pour des modes différents, 181 a l'air interessant.

Le "Central Heating" est remonté mais n'a pas l'air cohérent pour une clim.

En regardant les autres, j'ai l'impression que :
- 162/163 : min/max d'un réglage de température
- 295/296 : min/max d'un réglage de température
- 177 : réglage de la température souhaitée ?
- 294 : pas d'un réglage de température

Il doit y avoir une capability indiquant les possibilités de l'appareil (chauffage, chauffe-eau, clim, ...), ça pourrait être interessant de trouver laquelle pour pouvoir configurer les modes des entités climate correctement, ça pourrant se faire en se partageant le fichier Cozytouch.json présent dans le dossier config de HA (si la case a été cochée lors de l'installation) et en comparant. Des infos peuvent être un peu privées dedans (ville, numéro de série, ...) n'hésitez pas à les masquer avant de l'envoyer.

En attendant on peut se baser sur le modelId, d'ailleurs quel est le modelId remonté pour in TAKAO M3 ?

Je vais ajouter les infos trouvées, si vous voulez faire des tests les mappings se trouvent dans capability.py et model.py.
Il y a également un mode de debug dans l'application Cozytouch interessant (probablement oublié par les développeurs), activable avec un tap à 2 doigts en dehors d'un contrôle, l'activation de l'oeil en haut active un overlay avec les capabilities utilisés sur chaque page :

![1](https://github.com/gduteil/cozytouch/assets/12835977/932ef443-a1b3-4bd6-85bd-4c40c3aa86a4)
![2](https://github.com/gduteil/cozytouch/assets/12835977/71d9cbf3-86f7-491e-8429-0ec04f86ad1f)

Bonne soirée.

**Comment by gduteil** [comment]
Merci je vais regarder tout ça et oui le mode debug est assez pratique ;)

Au passage Je me demandais, je n'ai qu'un seul appareil, l'intégration arrive à s'en sortir avec plusieurs ?

**Comment by alicesalse-bmg** [comment]
J'ai fait une intégration pour chaque appareil ROOM_0 / ROOM_1.

CLIF je pense que c'est le HUB Naviclim. ensuite UI_0 et UI_1 je ne sais pas trop...

<img width="994" alt="image" src="https://github.com/gduteil/cozytouch/assets/147829707/3d285fb8-7c4d-4b68-b33a-0bfc4c089b4f">

**Comment by gduteil** [comment]
Vous avez 2 clims branchées sur un hub, lui même connecté en Wifi ?

Si c'est le cas, je pense effectivement que CLIF est le hub (179 a l'air d'être un niveau réception d'un signal Wifi), UI_x doivent être des interfaces internes pour la connexion entre clim et hub, et ROOM_x sont les clims, d'ailleurs CLIF et UI_x sont associées à une zone "zoneTechnique" qui est d'un type différent, probablement masquée dans l'application.

Je suis surpris par les modelId, tous différents
  - CLIF : 556
  - ROOM_0 : 557
  - ROOM_1 : 558
  - UI_0 : 562
  - UI_1 : 563

**Comment by alicesalse-bmg** [comment]
> Vous avez 2 clims connectées en Zigbee sur un hub, lui même connecté en Wifi ?
Oui c'est exactement ça.

> Je suis surpris par les modelId, tous différents
Mes 2 splits sont des TAKAO M3 mais pas la même puissance donc modèle différent (ASYG14KGTE / ASYG07KGTE) ce qui peut expliquer la différence d'ID. 🤔

j'ai complété mon commentaire précédent

**Comment by alicesalse-bmg** [comment]
Bonjour @gduteil,
est il possible de m'autoriser à créer une branche?

**Comment by gduteil** [comment]
> Voici donc ce que j'ai réussi à faire :
> 
> ![image](https://private-user-images.githubusercontent.com/147829707/307028262-7657c8d6-42a5-4866-b158-fa4af073242e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzI4NDksIm5iZiI6MTcwODYzMjU0OSwicGF0aCI6Ii8xNDc4Mjk3MDcvMzA3MDI4MjYyLTc2NTdjOGQ2LTQyYTUtNDg2Ni1iMTU4LWZhNGFmMDczMjQyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQyMDA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTI3ODdkOGEzOTMxZGI3ODRjNTg5NmQwNzcwZjNmZTNhNzViN2NiODIzZTkwMDFlNTFiMDY0NDVkODNkNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XWWbgBp3tDaqZkQRDDsKfwULjYJ5IqakZirWq1D6PJY)
> 
> ![image](https://private-user-images.githubusercontent.com/147829707/307062325-07f44b96-5c9e-47fb-914a-770237755333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzI4NDksIm5iZiI6MTcwODYzMjU0OSwicGF0aCI6Ii8xNDc4Mjk3MDcvMzA3MDYyMzI1LTA3ZjQ0Yjk2LTVjOWUtNDdmYi05MTRhLTc3MDIzNzc1NTMzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQyMDA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmQ2YTE5NTdmMWE1YzZkMDFlZWZkY2MxMTJjYTczZmQ3NjZlY2IwYjM0MGNiM2FjMGZmMjcwMzZhOGFkZWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.goQWbI8PPLCGAoDa3hBIJGyJyllOD2RmWipqzp1T-rg)
> 
> je pousse mes devs dans une branche. j'ai essayé de faire en sorte que ca prenne en compte votre config également, mais c'est à tester chez vous.

Bonne nouvelle ! 

il y a moyen d'ajouter d'autres elements sur l'entité climate, j'ai commencé à la rendre un peu plus configurable, je pense pouvoir commiter quelque chose ce week-end.

**Comment by gduteil** [comment]
> Bonjour @gduteil, est il possible de m'autoriser à créer une branche?

Je ne suis pas très à l'aise avec GitHub, vous avez dû recevoir une invitation, je devrais pouvoir gérer les droits une fois l'invitation acceptée

**Comment by alicesalse-bmg** [comment]
est ce que je peux vous pousser mes devs? sur une branche?

actuellement je n'y parvient pas
<img width="468" alt="image" src="https://github.com/gduteil/cozytouch/assets/147829707/915b498a-246e-42c7-a0ed-47f97a604d69">

**Comment by alicesalse-bmg** [comment]
désolé je n'avais pas vu l'invite : j'ai poussé ici https://github.com/gduteil/cozytouch/tree/dev/integ-takao-m3

**Comment by gduteil** [comment]
Merci je vais vérifier que ça n'a pas d'impact dans mon cas avec une Chaudière Naema.

Du coup le 117 remonte bien la température courante ? il n'avait pas l'air de fonctionner avant.

**Comment by alicesalse-bmg** [comment]
Pour moi le 117 est bloqué sur 23,5 et 16,2. Peut être les valeurs au moment ou j’ai initialisé les interfaces naviclim. Mais je n’ai pas de rafraîchissement depuis.

je ne vois pas d’autre paramètre qui pourrait indiquer la température ambiante.

peut être un bug dans le rafraîchissement au niveau de Cozytouch? Il y a forcément une sonde de température…

🤔 à suivre

**Comment by gduteil** [comment]
C'est effectivement assez étrange, 117 dans mon cas est la sonde de température du thermostat, et c'est surprenant que ça soit remonté par l'API avec des valeurs non nulles et cohérentes avec une température mais ne varient pas.

Il y a une température courante affichée dans Cozytouch ?

**Comment by alicesalse-bmg** [comment]
Non dans l’interface graphique il n’y a pas de température ambiante affichée.

![IMG_5441](https://github.com/gduteil/cozytouch/assets/147829707/4d6db043-2a86-4ba5-864d-96146fd9aedf)

dans les paramètres du mode debug il y a bien la valeur mais toujours la même 

![IMG_5442](https://github.com/gduteil/cozytouch/assets/147829707/88470b4e-4ab6-4730-ad5b-ad6ac33c3ed7)

sans doute un dev pas encore abouti…

**Comment by gduteil** [comment]
Si vous regardez la capture que j'ai envoyée avant-hier, j'ai la même page mais avec l'indication de température thermostat, ce qui peut vouloir dire qu'elle n'est affichée que si un thermostat d'ambiance est présent.

Dans le cas où il n'y n'est pas présent, la clim utiliserait une sonde interne pour sa régulation mais ne la remonte peut-être pas, et la valeur 117 reste à une ancienne valeur (valeur durant les tests usine ?)

**Comment by gduteil** [comment]
Bonsoir,

Je suis en train de finir un peu de refacto/nettoyage, je regarderai merger vos modifications ensuite.

Je voulais en profiter pour ajouter les modelId, pouvez-vous me dire lequels sont ASYG14KGTE et ASYG07KGTE ?
Le hub a un nom "commercial" ?

**Comment by alicesalse-bmg** [comment]
Bonjour,

ASYG14KGTE = 557
ASYG07KGTE = 558

Le hub c'est un HUB NAVICLIM = 556 (CLIF).

Pour les UI (562 et 563) je ne sais pas trop de toute façon ca ne semble rien remonter d'interessant et je ne sais pas dire laquelle correspond a quel climatiseur.

<img width="1364" alt="image" src="https://github.com/gduteil/cozytouch/assets/147829707/4e4e8bf6-b388-4388-ab9b-d0d73f895530">


Je n'ai pas encore pris le temps de faire les intégrations pour les position du volet / la vitesse de ventilation / le mode eco ...

Je vous laisse peut être le temps de consolider ce que j'ai déjà poussé et je le ferai ensuite.

**Comment by gduteil** [comment]
Le JSON indique que UI_0 est un enfant de ROOM_0, et UI_1 de ROOM_1, et effectivement vu ce qui remonte  ça n'a pas grand intérêt, je souhaitais juste ajouter l'identification.

Dans le commit d'hier soir j'ai ajouté les mode eco et powerful, ainsi que l'état presence en entités basiques, il me reste à finir de rendre l'entité climate plus paramétrable avant d'intégrer vos modifications, l'idée est d'avoir un descripteur d'appareils dans model.py et que les capteurs/contrôles s'adaptent en conséquence.

Je vais également regarder pour le côté traduction.

**Comment by gduteil** [comment]
Bonsoir,

Je suis en train d'intégrer vos modifications, je me pose une petite question concernant le mode "auto".
Je vois que vous l'avez considéré comme un mode "heat", ça ne serait pas plutôt un mode "heat_cool" qui donne une plage de température, en dessous ça passe en heat et au dessus en cool ?

**Comment by gduteil** [comment]
Je viens de faire un push qui devrait intégrer vos modifications, vu la refacto et le nettoyage que j'étais en train de faire je n'ai pas pu le faire automatiquement, je l'ai fait manuellement et adaptant, il est possible que j'ai oublié quelque chose.

Vous pouvez vérifier que ça fonctionne bien chez vous ?

**Comment by alicesalse-bmg** [comment]
Bonsoir,

J'ai poussé une branche avec quelques adaptations pour les clims TAKAO M3. #3

Pour les PRESET_MODES au départ j'avais pensé l'utiliser pour les modes ACTIVE (détecteur présence) / ECO / BOOST (powerful). Mais du coup on ne peut pas les cumuler avec la programmation. Je ne sais pas comment on pourrait faire, avez- vous une idée?

Est il possible que l'id de l'entité soit plutôt de type climate.room_0_air_conditionner ou sensor.room_0_capability_100000_2 au lieu de comme ci-dessous. Il me semble que c'était bien géré dans la première version. Mais je ne trouve plus a quel endroit on le configure.

<img width="555" alt="image" src="https://github.com/gduteil/cozytouch/assets/147829707/7a422fce-20fe-4e4a-aac2-42325a99ea97">

Bonne soirée.

**Comment by gduteil** [comment]
Bonsoir,

Je vais regarder pour merger la branche.

En cas de programmation active les modes autres modes sont supposés désactiver temporairement la programmation ? (Atlantic appelle "ça dérogation").

Pour les IDs d'entités, c'est une régression suite à la refact, je m'en suis rendu compte hier, essayez en intégrant les commits d'hier, puis en réinstallant les appareils, ça devrait être mieux.

**Comment by alicesalse-bmg** [comment]
bonjour,

Les modes « détecteur de présence » (se met en mode eco si pas de présence) / « eco » et « powerful » peuvent à priori être utilisés pendant la programmation. Les activer ne déclenche pas de dérogation.

Idéalement il faudrait que ce soit une autre catégorie de presets_modes. Mais il ne peut pas y en avoir  je suppose?

**Comment by gduteil** [comment]
L'entité climate n'a malheureusement qu'une seule liste de presets, il est peut-être possible de la surcharger pour la faire évoluer (au moins dans un dashboard, je pense que c'est fixe dans les paramètres), je n'ai jamais regardé cette partie.

J'avais ajouté prog/basic/override en tant que presets pour les chaudières qui n'ont pas de modes très complexes, on peut imaginer de les sortir de l'entité climate dans les cas des clims en tant que controles différents (switch, select ou autre) et de ne laisser dans les presets que les modes "utiles"

**Comment by alicesalse-bmg** [comment]
Bonsoir,

J'ai fait un petite correction, car j'avais une erreur sur le time.sleep()
> AttributeError: type object 'datetime.time' has no attribute 'sleep'

Puis j'ai intégré les presets ACTIVITY/ECO/BOOST pour les clims, en effet les programmes pouvant être finalement créés dans le home assistant,  cela me semble plus intéressant.

<img width="460" alt="image" src="https://github.com/gduteil/cozytouch/assets/147829707/4b8351a3-df0a-41b9-984b-f024f86084e1">

**Comment by gduteil** [comment]
Ca commence à ressembler à quelque chose ;) bravo et merci pour l'ajout.

J'ai validé le pull request, c'est surprenant pour l'import time, chez moi ça rentre en conflit avec datetime, je l'ai supprimé.
Vous pouvez réessayer avec le dernier main ou la 0.5 si ça fait toujours la même chose chez vous ?

**Comment by alicesalse-bmg** [comment]
Bonjour @gduteil,

Merci à vous pour tout le code de départ, je n'aurai pas été capable de le faire toute seule.

je viens de retester avec la v0.5,
le problème avec `datetime.time` c'est que j'ai ce message d'erreur à chaque fois que je modifie la température ou n'importe quel paramètre :

![image](https://github.com/gduteil/cozytouch/assets/147829707/5411228d-15bb-495d-9a5f-1a66abf98c6e)


Sinon autre petit bug constaté sur la v0.5 : 
![image](https://github.com/gduteil/cozytouch/assets/147829707/57204d9a-c552-4c9e-a639-ad1e2905eb32)

**Comment by gduteil** [comment]
C'est bizarre, je n'ai pas le message et avec l'import time j'ai des messages d'erreurs à cause d'un conflit avec datetime, je regarderai ce soir.

Pour le label manquant, j'ai déjà eu le cas et ça venait du cache du navigateur, vous pouvez essayer en forçant un rafraichissement ou en vidant le cache ?

**Comment by alicesalse-bmg** [comment]
pour le cache ca a bien fonctionné 👍🏽

**Comment by gduteil** [comment]
J'ai un peu de mal à comprendre l'intérêt d'avoir un objet time dans time et un autre dans datetime...

Je viens commiter une correction qui devrait corriger les problèmes de conflits.

**Comment by alicesalse-bmg** [comment]
Bonjour @gduteil,

Hier, j'ai fait des modifications sur mon wifi et j'ai du re-appairer mon Hub Naviclim. Etrangement mon capability 117 s'est ajusté avec de nouvelles temperatures : 20 et 24.5 et est maintenant bloqué sur celles-ci.
Cela confirme mon idée qu'il y a un souci sur le rafraichissement de ce paramètre. A suivre...

![image](https://github.com/gduteil/cozytouch/assets/147829707/f79c2b30-c2d8-4894-9b4d-044a8aafdd4e)

**Comment by gduteil** [comment]
Bonjour,

C'est effectivement surprenant que ces valeurs aient changées lors de la reconfiguration... j'ai remarqué que quand elle est affichée dans l'appli elle est correctement mise à jour, alors que quand elle n'est pas affichée elle n'est soit pas remontée par l'API, soit remontée avec une valeur incorrecte qui ne varie pas.

Autre sujet, j'ai trouvé des capabilities pour les consommations, mais je n'ai rien vu dans votre JSON qui pourrait correspondre, vous avez un suivi de la conso dans l'appli ?

**Comment by avidflyer17** [comment]
Bonjour,

Merci pour le travail. Pour la consommation, je n'ai rien dans l'appli avec le modèle takao M2: j'ai un message qui me dit que cette fonction n'est pas disponible pour mon installation.

Je ne sais pas si cela aide mais j'ai cette erreur dans les logs : 
`2024-10-13T10:14:16.037810034Z 2024-10-13 12:14:16.032 ERROR (MainThread) [custom_components.cozytouch.config_flow] Unexpected exception
2024-10-13T10:14:16.037869942Z Traceback (most recent call last):
2024-10-13T10:14:16.037881542Z   File "/config/custom_components/cozytouch/config_flow.py", line 51, in async_step_user
2024-10-13T10:14:16.037890306Z     hub = await validate_input(self.hass, user_input)
2024-10-13T10:14:16.037897584Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13T10:14:16.037904781Z   File "/config/custom_components/cozytouch/config_flow.py", line 28, in validate_input
2024-10-13T10:14:16.037912616Z     result = await hub.test_connection()
2024-10-13T10:14:16.037919822Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13T10:14:16.037927081Z   File "/config/custom_components/cozytouch/hub.py", line 97, in test_connection
2024-10-13T10:14:16.037934904Z     await self.connect()
2024-10-13T10:14:16.037942077Z   File "/config/custom_components/cozytouch/hub.py", line 119, in connect
2024-10-13T10:14:16.037949689Z     token = await response.json()
2024-10-13T10:14:16.037956954Z             ^^^^^^^^^^^^^^^^^^^^^
2024-10-13T10:14:16.037985650Z   File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1243, in json
2024-10-13T10:14:16.037993052Z     raise ContentTypeError(
2024-10-13T10:14:16.037998674Z aiohttp.client_exceptions.ContentTypeError: 403, message='Attempt to decode JSON with unexpected mimetype: application/xml; charset=utf-8', url='https://apis.groupe-atlantic.com/users/token'`

Sinon tout semble OK : 

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/c352e36f-ca77-4fca-a445-dca1f8f410fa">

<img width="382" alt="image" src="https://github.com/user-attachments/assets/10184766-022a-4ac7-ae7f-63cac57c10e4">

Merci encore pour votre travail.
