### ISSUE TITLE
Compatibilité OK avec Thermor Aeromax Split V3

### ISSUE THREAD

**Issue by Harckange** [gduteil/cozytouch#11]
Salut,

J'ai installé un nouveau ballon thermodynamique Thermor Aeromax Split V3, malheureusement Overkiz ne fonctionne pas. Lorsque je saisi les identifiants, j'obtiens le message d'erreur : Your CozyTouch hardware is not supported by this integration
Du coup j'ai testé ton intégration et là tout fonctionne parfaitement 😄 

Après avoir saisi mes identifiants, le chauffe eau est bien récupéré et tout s'affiche bien.

Un aperçu : 

![image](https://github.com/gduteil/cozytouch/assets/101645660/0b0fdf1f-1822-4b8d-b4f4-bd0098ccf073)

Les sensors qui sont récupérés : 

![image](https://github.com/gduteil/cozytouch/assets/101645660/67161ea6-6ce3-4e2d-a503-050f549b61eb)

Et aussi de nombreuses autres infos qui sont récupérées, mais je ne sais pas à quoi elles servent. Sauf peut-être celle tout en bas (encadrée en vert), je suppose qu'il s'agit de la température au fond du ballon sachant qu'on a déjà celle au milieu et celle en haut du ballon : 

![image](https://github.com/gduteil/cozytouch/assets/101645660/fbbd6b20-58fd-438c-a44a-9eec0e4fe00f)

Voilà, encore merci pour cette intégration. N'hésites pas si tu as besoin d'informations ou que je fasse des tests qui puissent faire avancer ton développement 🙌

**Comment by gduteil** [comment]
Salut,

Content que ça marche chez toi.

L'idéal est d'envoyer le fichier Cozytouch.json généré dans "/homeassistant" en ayant masqué au préalable les infos de localisation.

Il y a pas mal d'infos remontées mais pas encore identifiées, la plupart n'a pas vraiment d'intéret mais si tu vous passer une valeur qui change et qui semble correspondre à quelque chose (température d'un capteur, changement de mode, ...) n'hésites pas à m'en faire part.

Concernant la 267 effectivement c'est la température du fond du ballon, je l'ai déjà ajoutée dans la release qui devrait être dispo aujourd'hui, j'en profiterai pour ajouter l'identification de ton ballon, ça devrait faire fonctionner le "Heating Mode".

**Comment by Harckange** [comment]
hum je n'ai pas de fichier Cozytouch.json généré dans /homeassistant, ni ailleurs... en tout cas c'est ce que "find / -type f -name *Cozy*" me renvoi

**Comment by gduteil** [comment]
Tu as coché la case "Dump a JSON file with received data" lors de la configuration ?
Si ce n'est pas le cas tu peux supprimer et réinstaller le chauffe-eau en la cochant, ça gardera l'historique.

**Comment by Harckange** [comment]
Effectivement j'avais pas coché la case, donc pas de fichier généré. Du coup voilà le fichier json anonymisé.

Je n'ai pas trouvé beaucoup de valeurs a associer au fichier, seulement la capabilityID 121 qui corresponds à la version "HMI". Sur le chauffe eau. On y accède via Paramètres - Accès expert (OK pour continuer) - diagnostic - version logiciel

[Cozytouch.json](https://github.com/user-attachments/files/15525644/Cozytouch.json)

**Comment by gduteil** [comment]
Merci, je viens de publier la 0.7 avec ces ajouts.
