### ISSUE TITLE
Compatibilité Sauter Kelud 1750W Anthracite Standard

### ISSUE THREAD

**Issue by tomcastleman** [gduteil/cozytouch#13]
Bonjour,

Tout d'abord merci beaucoup @gduteil pour votre travail sur ce projet.

J'ai un seche-serviette Sauter Kelud 1750W Anthracite Standard qui est bien detecté mais il montre sur l'integration:

>  Unknown product (1382)

J'ai verifié et il manque le code `1382` [ici](https://github.com/gduteil/cozytouch/blob/main/custom_components/cozytouch/model.py#L220)

Ci-joint sont le [Cozytouch.json](https://github.com/user-attachments/files/16045279/Cozytouch.1.json)

Merci

**Comment by gduteil** [comment]
Bonjour,

Merci pour l'info, effectivement le modèle n'a pas le même identifiant que la version blanche.
Je vais l'ajouter pour la prochaine version.

En attendant tu peux dupliquer le 1381, ça devrait changer quelques entités et faire fonctionner l'override en cas de mode prog actif.

**Comment by gduteil** [comment]
Bonjour,

C'est ajouté dans la 0.9.

**Comment by tomcastleman** [comment]
Super merci @gduteil !
