### ISSUE TITLE
KELUD 1750W (Blanc) - Contrôle de la température impossible

### ISSUE THREAD

**Issue by AuroreVgn** [gduteil/cozytouch#14]
Bonjour,

J'utilise depuis quelque mois cette intégration pour contrôler dans HA mon KELUD 1750W (Blanc). Elle fonctionnait à merveille. 

Je l'utilise notamment pour faire une scène qui l'allume à 26°C (_number.kelud_1750w_blc_target_temperature_) pendant 1 heure (_number.kelud_1750w_blc_override_total_time_) afin de faire sécher les serviettes.
Une automatisation permet ensuite de l'éteindre.

Or, depuis hier (lien avec la mise à jour 2023.7.0 ???), seuls l'allumage et l'extinction fonctionnent correctement. 

Depuis HA, le contrôle de la température fonctionne aléatoirement que ce soit avec la carte 'climate' ou le slider de _number.kelud_1750w_blc_target_temperature_.
En effet, le message d'erreur apparait
<img width="675" alt="Erreur" src="https://github.com/gduteil/cozytouch/assets/74768535/7e63ae8d-a832-484a-a002-7626cb696c54">
Puis, parfois la température se met à jour dans l'appli CozyTouch et parfois pas.
Le même message d'erreur apparait dans la scène qui programme la température et, étonnement, dans l'automatisation qui l'éteint.

A noter, les modifications réalisées depuis l'appli CozyTouch sont prises en compte instantanément dans HA.

Version CozyTouch : 0.80.0
Version HA : Core 2024.7.0 / Supervisor 2024.06.2 / Operating System 12.4 / Frontend 20240703.0

**Comment by AuroreVgn** [comment]
Re,

J'ai tenté une correction rapide (et probablement pas très propre) : j'ai commenté la ligne 491 `time.sleep(1)` du fichier _custom_component > cozytouch > hub.py_, redémarré HA et le problème est résolu.

**Comment by gduteil** [comment]
Bonsoir,

Certaines capabilities prennent un peu de temps à être activées, et dans certains cas où il faut changer plusieurs valeurs successivement il faut attendre que les précedentes soient effectives pour que les suivantes soient acceptées, d'où cette partie du code qui interroge l'API pour savoir si la requête précedente est terminée avant de lancer la suivante.
Il me semble que le seul cas où c'est nécessaire est dans le cas d'un "override" (délégation) d'une consigne en étant en mode programmation, les sèche-serviettes n'ont pas de mode programmation il me semble, donc ça ne devrait pas poser de problème.

La dernière MAJ de HA n'a plus l'air d'accepter cette attente avec le time.sleep(1), je vais regarder ce week-end pour remplacer par une autre solution.

**Comment by gduteil** [comment]
Au final c'était pas grand chose à modifier, je viens de publier une 0.9.0, tu peux mettre à jour pour voir si ça fonctionne ?

**Comment by AuroreVgn** [comment]
Bonjour,

Merci pour ton retour. Le KELUD 1750W (Blanc) bien un mode programmation et donc un mode override que j'utilisais pour ma fameuse automatisation de séchage.
Je viens de faire la mise à jour 0.9.0 ainsi que de HA Core 2024.7.1 et cela fonctionne parfaitement ! Merci beaucoup !

**Comment by gduteil** [comment]
Parfait !
