### ISSUE TITLE
Merci beaucoup !

### ISSUE THREAD

**Issue by JSteunou** [gduteil/cozytouch#16]
Désolé de passer par ici, mais c'était juste pour dire merci car ça marche très bien et je suis bien content d'avoir pu ajouter mon sauter kelud :)

**Comment by gduteil** [comment]
Merci pour ce message, c'est toujours agréable ;)

**Comment by romainhe** [comment]
Hello @gduteil ! (je profite du ticket fermé pour ne pas polluer les issues ouvertes) 
Pareil, un grand merci pour cette trouvaille qui m'a sauvé... je viens d'installer le nouveau radiateur (Doris 2024) et je me suis retrouvé comme un c** avec aucun moyen de le connecter (HA/Overkiz/Tahoma/...) malgré ce qui est laissé entendre sur les nombreuses doc produit Atlantic. Et l'app officielle est juste horrible 🥲.

Je voulais en profiter aussi car une question me brûle les lèvres, où as-tu trouvé les infos concernant l'API ? Je trouve absolument aucune information la concernant et j'aurai aimé creuser le sujet de mon côté aussi.

Est-ce que l'appareil est accessible sur le réseau local par exemple (j'avais réussi à accéder à une interface un temps, puis elle est devenue indisponible d'un coup).

(Si jamais tu es d'accord et que tu as un discord ou autre pour échanger je suis preneur 👍)

Bonne soirée en attendant !
