### ISSUE TITLE
Non compatible Thermor Cozytouch

### ISSUE THREAD

**Issue by patafx** [gduteil/cozytouch#8]
Bonjour,

j'ai essayé de me connecter avec ma solution thermor cozytouch qui a mon avis est identique mais cela ne fonctionne pas.

**Comment by gduteil** [comment]
Bonjour,

Le login/MDP sont acceptés mais la liste est vide ?

**Comment by patafx** [comment]
Non ils ne sont pas accepté.

j'ai essayé de télécharger l'application Atlantic Android et mes credentials sont refusé aussi

**Comment by gduteil** [comment]
L'ajout via Overkiz dit quoi ?

**Comment by patafx** [comment]
Idem, de plus par rapport au tuto sur overkiz il n'y a pas l'option thermor cozytouch, uniquement atlantic cozytouch

**Comment by patafx** [comment]
Bon c'était un problème de login mal enregistré dans mon dashlane.
Tout est rentrer dans l'ordre désolé pour le dérangement.

**Comment by gduteil** [comment]
Effectivement Thermor Cozytouch est marqué supporté par Overkiz mais n'est pas dans la liste, il y a des chances pour que le protocole soit identique à un des 2 utilisé par Atlantic mais que l'adresse du serveur diffère.

Il faudrait réussir à capturer les messages entre venant de l'appli mobile pour savoir quel protocole et quel serveur sont utilisés.

Ce n'est pas forcément simple à mettre en route, j'ai gardé ce j'avais utilisé pour Atlantic, je peux éventuellement faire ces captures et analyser, en revanche il me faudrait un login/MDP qui fonctionne sur l'appli mobile. On peut envisager un changement temporaire de ce MDP que tu me communiques (par e-mail, pas dans cette issue) le temps de faire cette analyse

**Comment by gduteil** [comment]
Du coup ça fonctionne avec Overkiz ou cette intégration ?

**Comment by patafx** [comment]
Overkiz, et ja vais testé avec votre intégration.

**Comment by themouette** [comment]
Juste pour dire que j'ai le même problème, quand je me connecte j'obtiens: `No new device found`

<img width="379" alt="image" src="https://github.com/user-attachments/assets/103957f2-2fe1-457f-a86c-9759ce3198b7" />
