### ISSUE TITLE
Fix partial support of Atlantic/Futjisu AC Split ASYG 12 KMTE

### ISSUE THREAD

**Issue by bnzbnz** [gduteil/cozytouch#9]
Hello gduteil,

I have 2 Splits and 1 K7 at home. Your plugin works perfectly with 2 of them (1 split and the K7).
Now the third one seems to have only partial support or erroneous...

Could you fix this? I'll provide all the data you may need....

Cordialement ;)
Laurent.

(![Screenshot 2024-05-29 113032](https://github.com/gduteil/cozytouch/assets/32573002/c1ad3992-b02c-4691-8cbc-7844eed1f107))

**Comment by gduteil** [comment]
Hello,

Can you send me the Cozytouch.json file ? 

It should be located in /homeassistant folder, if it's not present you need to reinstall one of your device and select "Dump a JSON file with received data" during configuration.

This file will contain some private informations (location, serial number, ...), you can remove them before sending.

**Comment by bnzbnz** [comment]
Hi,

I have the file ready where should I send it ?

**Comment by bnzbnz** [comment]
Here you are...
[Cozytouch.json](https://github.com/gduteil/cozytouch/files/15490062/Cozytouch.json)

Thank you!

**Comment by gduteil** [comment]
Thank you.

You seem to have 3 different devices, 2 of them are recognized as Takao M3 5.4kW (modelId 557) Takao M3 2kW (modelId 558), the last one (modelId 559) is not recognized, can you confirm the first 2 models are correct and give details about the third one ?

I will be able to add the identification this weekend, if you want to do some tests before you can modify the model.py file to add the missing one

**Comment by gduteil** [comment]
I added the identification for the ASYG 12 KMTE in the main branch, can you check if it's ok now ?

To install it you need to select the integration in HACS, go to menu with the 3 dots in the top right corner and download it again, selecting the "main" version.

**Comment by bnzbnz** [comment]
Perfect! It works seamlessly...
Thank you.
Laurent.

**Comment by bnzbnz** [comment]
Is there a way to donate ?

**Comment by gduteil** [comment]
I'm glad this worked, I will probably release a new version tomorrow.

You can donate using Paypal if you want (gduteil@gmail.com), thank you !
